// New Brunswick judo, coached in Dieppe: French is not a nice-to-have here,
// it is the first language of a real share of the membership. So `Copy` is a
// real TypeScript type, not a loose Record<string, string> - the FR object
// below is checked against the exact same shape as EN, so the compiler
// refuses to build if a French string is ever missing rather than silently
// falling back to English at runtime.

export const EN = {
  code: 'EN',
  langName: 'English',
  nav: { home: 'Home', about: 'About Otoshi', schedule: 'Schedule', contact: 'Contact Us', cta: 'Join Club Otoshi' },
  hero: {
    eyebrow: 'Martial Art · Greater Moncton',
    title: 'Judo Otoshi',
    sub: 'Find unbreakable confidence and focus, one belt at a time.',
    cta: 'Join Club Otoshi',
    alt: 'See our programs',
    locationLabel: 'Club Location',
    location: '1571 Melanson Rd, Dieppe',
    phoneLabel: 'Call the Dojo',
  },
  community: {
    items: [
      {
        title: 'One Home Dojo, Deep Roots',
        body: 'Training in Dieppe since 2012 – the same coaching staff, the same community, growing every year across the Greater Moncton area.',
      },
      {
        title: 'Certified Judo Instructors',
        body: 'Train under experienced, certified Senseis dedicated to safety, character development, and proven technical instruction.',
      },
      {
        title: 'Family-First Value & Support',
        body: 'We encourage family training with significant multi-sign-up discounts and age-specific classes for total family growth.',
      },
    ],
  },
  why: {
    eyebrow: 'Why families choose Otoshi',
    title: 'The right guide for your family.',
    stats: [
      { value: '78%', label: 'Self-confidence' },
      { value: '78%', label: 'Social skills (youth)' },
      { value: '56%', label: 'Openness' },
    ],
    footnote: 'IJF studies show that judo builds youth confidence, social skills, and personal growth.',
  },
  programs: {
    eyebrow: 'Judo Classes',
    title: 'A class for every age and skill level.',
    items: [
      { key: 'beginner', img: 'Beginner.jpg', name: 'Beginner', ages: 'Ages 6–13', body: 'New to judo. Falling safely, balance, and the first throws, in a structured and encouraging class.' },
      { key: 'intermediate', img: 'Intermediates-regular.jpg', name: 'Intermediate', ages: 'Ages 8–13', body: 'A few years of experience. Building technique and ring craft toward the next belt.' },
      { key: 'elite', img: 'Elites.jpg', name: 'Elite', ages: 'Ages 13+', body: 'The competitive program, for judoka training toward tournaments and provincial standards.' },
      { key: 'adult', img: 'Adults.jpg', name: 'Adult', ages: 'Ages 14+', body: 'All levels welcomed. Strength, discipline, and real self-defense, on your own schedule.' },
    ],
    trial: { title: 'Just getting started?', body: 'Step onto the mat with a free trial and discover Otoshi Judo.', cta: 'Step Onto the Mat' },
  },
  who: {
    eyebrow: 'Who we are',
    title: 'The meaning behind the name.',
    body: 'In judo, "otoshi" (落とし) means "drop" or "fall" – part of several throwing techniques, including Tai Otoshi (body drop) and Tani Otoshi (valley drop), classified as Sutemi Waza, sacrifice techniques.',
    body2: 'Founded in Dieppe in 2012, Otoshi has grown into a community of more than 200 judoka, coached by eight certified Senseis under Technical Director Stéphane Bérubé – built on discipline, respect, and a genuine love of the sport.',
    figure: '2012', figureLabel: 'founded in Dieppe',
    figure2: '200+', figureLabel2: 'judoka in our community',
  },
  schedule: {
    eyebrow: 'About Otoshi',
    title: 'Class schedule – Dieppe',
    jumpCta: 'Find Class Times',
    address: '1571 Melanson Rd, Dieppe, NB',
    rows: [
      { day: 'Mon – Fri', time: '7:00 – 8:00 am', level: 'Morning conditioning' },
      { day: 'Mon – Fri', time: '3:00 – 4:30 pm', level: 'Student-athlete program' },
      { day: 'Mon – Fri', time: '5:00 – 7:00 pm', level: 'Beginner' },
      { day: 'Mon – Fri', time: '5:00 – 7:30 pm', level: 'Intermediate A & B' },
      { day: 'Mon – Fri', time: '7:00 – 9:00 pm', level: 'Elite training' },
      { day: 'Mon – Fri', time: '7:30 – 9:00 pm', level: 'Adult / Teen' },
      { day: 'Saturday', time: '9:00 – 9:45 am', level: 'Ninja (ages 4–6)' },
      { day: 'Saturday', time: '10:00 am – 12:00 pm', level: 'Advanced' },
    ],
    footnote: 'Ninja is the early pathway into Beginner – the same mat, a gentler pace.',
  },
  judoForAll: {
    eyebrow: 'Judo For All',
    title: 'A path in for newcomers of any age.',
    body: 'A program designed to welcome newcomers of all ages and abilities into judo, in a supportive, structured, and fun environment.',
    benefits: ['Confidence and self-discipline', 'Cultural connection', 'Community and belonging', 'Stress relief and mental well-being', 'Respect and teamwork'],
    cta: 'Register Now',
  },
  sponsors: { label: 'Thank you to our sponsors' },
  cta: {
    eyebrow: 'Ready to start?',
    title: 'Step onto the mat.',
    sub: 'Free trial class, no obligation. Come see what a few years on the mat can build.',
    button: 'Join Club Otoshi',
    or: 'or call',
  },
  contact: {
    eyebrow: 'Contact Us',
    dojoLabel: 'Dojo',
    hoursLabel: 'Hours',
    hours: 'Monday – Friday: 5:00–6:00pm, 7:30–9:00pm',
    hours2: 'Saturday: 9:00am – 12:00pm',
    directions: 'Get Directions',
    followLabel: 'Follow along',
  },
  footer: {
    affiliation: 'Proudly supported by',
    bonaFideNote: 'logo to be confirmed',
    rights: 'Judo Otoshi. All rights reserved.',
    terms: 'Terms of Use',
    privacy: 'Privacy Policy',
  },
  register: {
    pageTitle: 'Register',
    backToSite: 'Back to site',
    steps: ['Parent / Guardian', 'Emergency Contact', 'Registration', 'Agreements'],
    step1: {
      title: 'Parent / Guardian Information',
      fullName: 'Full Name',
      email: 'Email',
      emailHint: 'Used to send registration details and updates from the Otoshi team.',
      phone: 'Phone',
      address: 'Address',
      city: 'City',
      province: 'Province',
      postalCode: 'Postal Code',
    },
    step2: {
      title: 'Emergency Contact Information',
      name: 'Emergency Contact Name',
      relationship: 'Relationship with Participant',
      phone: 'Emergency Contact Phone',
    },
    step3: {
      title: 'Registration',
      kids: 'Number of kids',
      adults: 'Number of adults',
      participant: 'Participant',
      kidLabel: 'Kid',
      adultLabel: 'Adult',
      class: 'Class',
      chooseClass: 'Choose a class…',
      schedulePrice: 'Schedule & Price',
      firstName: 'First Name',
      lastName: 'Last Name',
      dob: 'Date of Birth',
      gender: 'Gender',
      male: 'Male',
      female: 'Female',
      notes: 'Illnesses / Allergies / Injuries',
      notesHint: 'Optional',
      atLeastOneClass: 'Select at least one class to continue.',
      subtotal: 'Subtotal',
      fee: 'Square processing fee',
      total: 'Total',
      pricingNote: 'Provisional pricing, pending final confirmation from the club.',
    },
    step4: {
      title: 'Required Agreements',
      judoNbTitle: 'Awareness and Assumption of Risk, Release of Liability, Waiver of Claims and Indemnity Agreement',
      judoNbBody: [
        'AWARENESS AND ASSUMPTION OF RISK',
        'I am aware that Judo involves risks including risk of personal injury, death, property damage, expense and related loss, including loss of income. Included in these risks are negligence on the part of Judo NB, its directors, officers, staff, officials, member clubs, volunteers, Judo Canada, other participants and owners of the facilities where activities occur. I freely accept and fully assume all such risks and the possibility of personal injury, death, property damage, expense and related loss, including loss of income.',
        'RELEASE OF LIABILITY, WAIVER OF CLAIMS AND INDEMNITY AGREEMENT',
        'In consideration of Judo NB accepting my application to participate in Judo activities, I agree:',
        '1. To waive any and all claims that may I have in the future against Judo NB, its directors, officers, staff, officials, member clubs, volunteers, Judo Canada, other participants and owners of the facilities where activities occur.',
        '2. To release Judo NB, its directors, officers, staff, officials, member clubs, volunteers, Judo Canada, other participants and owners of the facilities where activities occur from any and all liability for any personal injury, death, property damage, expense and related loss, including loss of income that I or my next of kin may suffer as a result of my participation in this activity, due to any cause whatsoever, including negligence, breach of contract or breach of any statutory duty of care.',
        '3. To hold harmless and indemnify Judo NB, its directors, officers, staff, officials, member clubs, volunteers, Judo Canada, other participants and owners of the facilities where activities occur from any and all liability for any damage to property of, or personal injury to, any third party, resulting from my participation in this activity.',
        '4. To allow the use of my name, photographic image, and relevant personal information for the promotion of judo in the media, judo related publications & websites, and for use by governing judo associations, when deemed appropriate by Judo NB.',
      ],
      clubTitle: 'Club Otoshi Waiver',
      clubBody: [
        'I understand and agree that in participating in any Judo class, workshop, rehearsal or performance, there is a possibility of physical injury or death. I voluntarily agree, therefore, to assume all risks and responsibility for any such injury or accident, which might occur to me or my child during any of OTOSHI’s classes, rehearsals, performances, or activities. I also exempt, release, and indemnify OTOSHI, its owners, agents, volunteers, assistants, employees, faculty members, and/or students from any and all liability claims, demands, or causes of action whatsoever from any damage, loss, injury, or death to me, my children, or property which may arise out of or in connection with participation in any classes or activities conducted by OTOSHI. I further hereby voluntarily agree to waive my rights and that of my heirs and assigns to hold OTOSHI, its owners, agents, volunteers, assistants, employees, faculty members, and/or students liable for such damage, loss, injury, or death. I understand that I should be aware of my physical limitations and agree not to exceed them. If I am signing this waiver for my children, I certify that I am the parent or legal guardian and have the right to waive these rights. Permission is granted to OTOSHI to use photographs of members for publicity purposes.',
        'The novel coronavirus, COVID-19, has been declared a worldwide pandemic by the World Health Organization. COVID-19 is extremely contagious and is believed to spread mainly from person-to-person contact. As a result, federal, provincial, and local governments and federal and provincial health agencies recommend social distancing and have, in many locations, prohibited the congregation of groups of people. OTOSHI has put in place preventative measures to reduce the spread of COVID-19; however, OTOSHI cannot guarantee that you or your child(ren) will not become infected with COVID-19. Further, attending OTOSHI could increase your risk and your child(ren)’s risk of contracting COVID-19. By signing this agreement, I acknowledge the contagious nature of COVID-19 and voluntarily assume the risk that my child(ren) and I may be exposed to or infected by COVID-19 by attending OTOSHI and that such exposure or infection may result in personal injury, illness, permanent disability or death. I understand that the risk of becoming exposed to or infected by COVID-19 at OTOSHI may result from the actions, omissions, or negligence of myself and others, including, but not limited to, OTOSHI employees, instructors, and program participants and their families. I voluntarily agree to assume all of the foregoing risks and accept sole responsibility for any injury to my child(ren) or myself (including, but not limited to, personal injury, disability, and death), illness, damage, loss, claim, liability, or expense, of any kind, that I or my child(ren) may experience or incur in connection with my child(ren)’s attendance at OTOSHI Judo or participation in OTOSHI classes (“Claims”). On my behalf, and on behalf of my children, I hereby release, covenant not to sue, discharge, and hold harmless OTOSHI, its employees, agents, and representatives, of and from the Claims, including all liabilities, claims, actions, damages, costs or expenses of any kind arising out of or relating thereto. I understand and agree that this release includes any Claims based on the actions, omissions, or negligence of OTOSHI, its employees, agents, and representatives, whether a COVID-19 infection occurs before, during, or after participation in OTOSHI.',
      ],
      legalEnglishOnlyNote: 'This legal text is currently available in English only - the same wording used on the previous registration form.',
      agree: 'I have read and agree to the above',
      mustAgree: 'Both waivers must be checked to submit your registration.',
    },
    stepNav: { next: 'Next', back: 'Back', submit: 'Submit Registration', submitting: 'Sending…' },
    required: 'This field is required.',
    success: {
      title: 'Registration received!',
      body: 'We’ve sent your registration to the Otoshi team - they’ll be in touch shortly.',
      paymentNote: 'Payment isn’t collected here yet. The club will follow up separately about paying through Square.',
      backHome: 'Back to home',
    },
    error: {
      title: 'Something went wrong',
      body: 'We couldn’t send your registration. Please try again, or contact the club directly.',
    },
  },
};

export type Copy = typeof EN;

export const FR: Copy = {
  code: 'FR',
  langName: 'Français',
  nav: { home: 'Accueil', about: 'À propos d’Otoshi', schedule: 'Horaire', contact: 'Contactez-nous', cta: 'Joindre le Club Otoshi' },
  hero: {
    eyebrow: 'Art martial · Grand Moncton',
    title: 'Judo Otoshi',
    sub: 'Une confiance inébranlable et une concentration à toute épreuve, une ceinture à la fois.',
    cta: 'Joindre le Club Otoshi',
    alt: 'Voir nos programmes',
    locationLabel: 'Emplacement du club',
    location: '1571, chemin Melanson, Dieppe',
    phoneLabel: 'Appeler le dojo',
  },
  community: {
    items: [
      {
        title: 'Un dojo, des racines profondes',
        body: 'À Dieppe depuis 2012 : la même équipe d’entraîneurs, la même communauté, en croissance chaque année dans le Grand Moncton.',
      },
      {
        title: 'Instructeurs de judo certifiés',
        body: 'Entraînez-vous avec des Senseis expérimentés et certifiés, dévoués à la sécurité, au développement du caractère et à un enseignement technique éprouvé.',
      },
      {
        title: 'Priorité à la famille',
        body: 'Nous encourageons l’entraînement en famille grâce à des rabais importants pour les inscriptions multiples et des cours adaptés à chaque âge.',
      },
    ],
  },
  why: {
    eyebrow: 'Pourquoi les familles choisissent Otoshi',
    title: 'La bonne voie pour votre famille.',
    stats: [
      { value: '78%', label: 'Confiance en soi' },
      { value: '78%', label: 'Habiletés sociales (jeunesse)' },
      { value: '56%', label: 'Ouverture d’esprit' },
    ],
    footnote: 'Des études de la FIJ démontrent que le judo développe la confiance, les habiletés sociales et la croissance personnelle des jeunes.',
  },
  programs: {
    eyebrow: 'Cours de judo',
    title: 'Un cours pour chaque âge et chaque niveau.',
    items: [
      { key: 'beginner', img: 'Beginner.jpg', name: 'Débutant', ages: 'De 6 à 13 ans', body: 'Nouveau au judo. Bien tomber, l’équilibre et les premières projections, dans un cours structuré et encourageant.' },
      { key: 'intermediate', img: 'Intermediates-regular.jpg', name: 'Intermédiaire', ages: 'De 8 à 13 ans', body: 'Quelques années d’expérience. On développe la technique et le sens du combat vers la prochaine ceinture.' },
      { key: 'elite', img: 'Elites.jpg', name: 'Élite', ages: '13 ans et plus', body: 'Le programme compétitif, pour les judokas qui s’entraînent vers les tournois et les standards provinciaux.' },
      { key: 'adult', img: 'Adults.jpg', name: 'Adulte', ages: '14 ans et plus', body: 'Tous les niveaux sont bienvenus. Force, discipline et défense personnelle réelle, selon votre horaire.' },
    ],
    trial: { title: 'Vous débutez?', body: 'Montez sur le tatami avec un cours d’essai gratuit et découvrez Judo Otoshi.', cta: 'Montez sur le tatami' },
  },
  who: {
    eyebrow: 'Qui nous sommes',
    title: 'La signification du nom.',
    body: 'En judo, « otoshi » (落とし) signifie « chute » ou « tombée » – une composante de plusieurs techniques de projection, dont le Tai Otoshi (chute du corps) et le Tani Otoshi (chute de la vallée), classées parmi les Sutemi Waza, les techniques de sacrifice.',
    body2: 'Fondé à Dieppe en 2012, Otoshi est devenu une communauté de plus de 200 judokas, encadrée par huit Senseis certifiés sous la direction technique de Stéphane Bérubé – bâtie sur la discipline, le respect et un amour sincère du sport.',
    figure: '2012', figureLabel: 'fondé à Dieppe',
    figure2: '200+', figureLabel2: 'judokas dans notre communauté',
  },
  schedule: {
    eyebrow: 'À propos d’Otoshi',
    title: 'Horaire des cours – Dieppe',
    jumpCta: 'Trouver l’horaire',
    address: '1571, chemin Melanson, Dieppe (N.-B.)',
    rows: [
      { day: 'Lun – Ven', time: '7 h – 8 h', level: 'Conditionnement matinal' },
      { day: 'Lun – Ven', time: '15 h – 16 h 30', level: 'Programme étudiant-athlète' },
      { day: 'Lun – Ven', time: '17 h – 19 h', level: 'Débutant' },
      { day: 'Lun – Ven', time: '17 h – 19 h 30', level: 'Intermédiaire A et B' },
      { day: 'Lun – Ven', time: '19 h – 21 h', level: 'Entraînement élite' },
      { day: 'Lun – Ven', time: '19 h 30 – 21 h', level: 'Adulte / Ado' },
      { day: 'Samedi', time: '9 h – 9 h 45', level: 'Ninja (4 à 6 ans)' },
      { day: 'Samedi', time: '10 h – 12 h', level: 'Avancé' },
    ],
    footnote: 'Ninja est la voie d’entrée vers Débutant – le même tatami, un rythme plus doux.',
  },
  judoForAll: {
    eyebrow: 'Judo pour tous',
    title: 'Une porte d’entrée pour les nouveaux venus, à tout âge.',
    body: 'Un programme conçu pour accueillir les nouveaux venus de tout âge et de tout niveau dans le judo, dans un environnement structuré, encourageant et amusant.',
    benefits: ['Confiance et autodiscipline', 'Connexion culturelle', 'Communauté et appartenance', 'Gestion du stress et bien-être mental', 'Respect et esprit d’équipe'],
    cta: 'S’inscrire maintenant',
  },
  sponsors: { label: 'Merci à nos commanditaires' },
  cta: {
    eyebrow: 'Prêt à commencer?',
    title: 'Montez sur le tatami.',
    sub: 'Cours d’essai gratuit, sans obligation. Venez voir ce que quelques années sur le tatami peuvent bâtir.',
    button: 'Joindre le Club Otoshi',
    or: 'ou appelez le',
  },
  contact: {
    eyebrow: 'Contactez-nous',
    dojoLabel: 'Dojo',
    hoursLabel: 'Heures',
    hours: 'Lundi – vendredi : 17 h – 18 h, 19 h 30 – 21 h',
    hours2: 'Samedi : 9 h – 12 h',
    directions: 'Obtenir l’itinéraire',
    followLabel: 'Suivez-nous',
  },
  footer: {
    affiliation: 'Fièrement soutenu par',
    bonaFideNote: 'logo à confirmer',
    rights: 'Judo Otoshi. Tous droits réservés.',
    terms: 'Conditions d’utilisation',
    privacy: 'Politique de confidentialité',
  },
  register: {
    pageTitle: 'Inscription',
    backToSite: 'Retour au site',
    steps: ['Parent / tuteur', 'Contact d’urgence', 'Inscription', 'Ententes'],
    step1: {
      title: 'Renseignements du parent / tuteur',
      fullName: 'Nom complet',
      email: 'Courriel',
      emailHint: 'Utilisé pour envoyer les détails d’inscription et les mises à jour de l’équipe Otoshi.',
      phone: 'Téléphone',
      address: 'Adresse',
      city: 'Ville',
      province: 'Province',
      postalCode: 'Code postal',
    },
    step2: {
      title: 'Renseignements du contact d’urgence',
      name: 'Nom du contact d’urgence',
      relationship: 'Lien avec le participant',
      phone: 'Téléphone du contact d’urgence',
    },
    step3: {
      title: 'Inscription',
      kids: 'Nombre d’enfants',
      adults: 'Nombre d’adultes',
      participant: 'Participant',
      kidLabel: 'Enfant',
      adultLabel: 'Adulte',
      class: 'Cours',
      chooseClass: 'Choisir un cours…',
      schedulePrice: 'Horaire et prix',
      firstName: 'Prénom',
      lastName: 'Nom de famille',
      dob: 'Date de naissance',
      gender: 'Sexe',
      male: 'Masculin',
      female: 'Féminin',
      notes: 'Maladies / Allergies / Blessures',
      notesHint: 'Optionnel',
      atLeastOneClass: 'Sélectionnez au moins un cours pour continuer.',
      subtotal: 'Sous-total',
      fee: 'Frais de traitement Square',
      total: 'Total',
      pricingNote: 'Tarification provisoire, en attente de confirmation finale du club.',
    },
    step4: {
      title: 'Ententes requises',
      // Legal text kept verbatim in English, same as the previous registration
      // form's own version - not translated here, since inventing a French
      // rendering of binding waiver language isn't something to guess at.
      // `legalEnglishOnlyNote` below (in French) says so plainly rather than
      // silently switching languages on the reader.
      judoNbTitle: 'Awareness and Assumption of Risk, Release of Liability, Waiver of Claims and Indemnity Agreement',
      judoNbBody: [
        'AWARENESS AND ASSUMPTION OF RISK',
        'I am aware that Judo involves risks including risk of personal injury, death, property damage, expense and related loss, including loss of income. Included in these risks are negligence on the part of Judo NB, its directors, officers, staff, officials, member clubs, volunteers, Judo Canada, other participants and owners of the facilities where activities occur. I freely accept and fully assume all such risks and the possibility of personal injury, death, property damage, expense and related loss, including loss of income.',
        'RELEASE OF LIABILITY, WAIVER OF CLAIMS AND INDEMNITY AGREEMENT',
        'In consideration of Judo NB accepting my application to participate in Judo activities, I agree:',
        '1. To waive any and all claims that may I have in the future against Judo NB, its directors, officers, staff, officials, member clubs, volunteers, Judo Canada, other participants and owners of the facilities where activities occur.',
        '2. To release Judo NB, its directors, officers, staff, officials, member clubs, volunteers, Judo Canada, other participants and owners of the facilities where activities occur from any and all liability for any personal injury, death, property damage, expense and related loss, including loss of income that I or my next of kin may suffer as a result of my participation in this activity, due to any cause whatsoever, including negligence, breach of contract or breach of any statutory duty of care.',
        '3. To hold harmless and indemnify Judo NB, its directors, officers, staff, officials, member clubs, volunteers, Judo Canada, other participants and owners of the facilities where activities occur from any and all liability for any damage to property of, or personal injury to, any third party, resulting from my participation in this activity.',
        '4. To allow the use of my name, photographic image, and relevant personal information for the promotion of judo in the media, judo related publications & websites, and for use by governing judo associations, when deemed appropriate by Judo NB.',
      ],
      clubTitle: 'Club Otoshi Waiver',
      clubBody: [
        'I understand and agree that in participating in any Judo class, workshop, rehearsal or performance, there is a possibility of physical injury or death. I voluntarily agree, therefore, to assume all risks and responsibility for any such injury or accident, which might occur to me or my child during any of OTOSHI’s classes, rehearsals, performances, or activities. I also exempt, release, and indemnify OTOSHI, its owners, agents, volunteers, assistants, employees, faculty members, and/or students from any and all liability claims, demands, or causes of action whatsoever from any damage, loss, injury, or death to me, my children, or property which may arise out of or in connection with participation in any classes or activities conducted by OTOSHI. I further hereby voluntarily agree to waive my rights and that of my heirs and assigns to hold OTOSHI, its owners, agents, volunteers, assistants, employees, faculty members, and/or students liable for such damage, loss, injury, or death. I understand that I should be aware of my physical limitations and agree not to exceed them. If I am signing this waiver for my children, I certify that I am the parent or legal guardian and have the right to waive these rights. Permission is granted to OTOSHI to use photographs of members for publicity purposes.',
        'The novel coronavirus, COVID-19, has been declared a worldwide pandemic by the World Health Organization. COVID-19 is extremely contagious and is believed to spread mainly from person-to-person contact. As a result, federal, provincial, and local governments and federal and provincial health agencies recommend social distancing and have, in many locations, prohibited the congregation of groups of people. OTOSHI has put in place preventative measures to reduce the spread of COVID-19; however, OTOSHI cannot guarantee that you or your child(ren) will not become infected with COVID-19. Further, attending OTOSHI could increase your risk and your child(ren)’s risk of contracting COVID-19. By signing this agreement, I acknowledge the contagious nature of COVID-19 and voluntarily assume the risk that my child(ren) and I may be exposed to or infected by COVID-19 by attending OTOSHI and that such exposure or infection may result in personal injury, illness, permanent disability or death. I understand that the risk of becoming exposed to or infected by COVID-19 at OTOSHI may result from the actions, omissions, or negligence of myself and others, including, but not limited to, OTOSHI employees, instructors, and program participants and their families. I voluntarily agree to assume all of the foregoing risks and accept sole responsibility for any injury to my child(ren) or myself (including, but not limited to, personal injury, disability, and death), illness, damage, loss, claim, liability, or expense, of any kind, that I or my child(ren) may experience or incur in connection with my child(ren)’s attendance at OTOSHI Judo or participation in OTOSHI classes (“Claims”). On my behalf, and on behalf of my children, I hereby release, covenant not to sue, discharge, and hold harmless OTOSHI, its employees, agents, and representatives, of and from the Claims, including all liabilities, claims, actions, damages, costs or expenses of any kind arising out of or relating thereto. I understand and agree that this release includes any Claims based on the actions, omissions, or negligence of OTOSHI, its employees, agents, and representatives, whether a COVID-19 infection occurs before, during, or after participation in OTOSHI.',
      ],
      legalEnglishOnlyNote: 'Ce texte légal est actuellement disponible en anglais seulement - le même texte utilisé sur l’ancien formulaire d’inscription.',
      agree: 'J’ai lu et j’accepte ce qui précède',
      mustAgree: 'Les deux décharges doivent être cochées pour soumettre votre inscription.',
    },
    stepNav: { next: 'Suivant', back: 'Retour', submit: 'Soumettre l’inscription', submitting: 'Envoi en cours…' },
    required: 'Ce champ est requis.',
    success: {
      title: 'Inscription reçue!',
      body: 'Nous avons envoyé votre inscription à l’équipe d’Otoshi - elle communiquera avec vous sous peu.',
      paymentNote: 'Le paiement n’est pas encore collecté ici. Le club vous contactera séparément au sujet du paiement par Square.',
      backHome: 'Retour à l’accueil',
    },
    error: {
      title: 'Une erreur s’est produite',
      body: 'Nous n’avons pas pu envoyer votre inscription. Veuillez réessayer ou contacter le club directement.',
    },
  },
};

export type Lang = 'en' | 'fr';
export const COPY: Record<Lang, Copy> = { en: EN, fr: FR };
